name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: '0 2 * * 2,5' # Runs at 2:00 AM every Tuesday and Friday https://medium.com/@muhdfarseen/a-simple-hack-for-bypassing-supabase-pausing-03fa1d94a41e

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install @supabase/supabase-js

      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          node -e "
          const { createClient } = require('@supabase/supabase-js');
          const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
          supabase.from('users').select('is_verified').limit(1).then(console.log).catch(console.error);
          "
